# Generated by CMake

set(PACKAGE_ITEMS mbedcrypto mbedx509 mbedtls)
cmake_path(GET CMAKE_CURRENT_LIST_DIR PARENT_PATH PACKAGE_DIR)
set(PACKAGE_DIR "${PACKAGE_DIR}/targets")

message(STATUS "Using package ${CMAKE_FIND_PACKAGE_NAME} in ${PACKAGE_DIR}/${HOST}/${PLATFORM}")

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget ${PACKAGE_ITEMS})
  set(_expectedTarget ${PACKAGE_NAME}::${_expectedTarget})
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)

if(MSVC)
set(PACKAGE_EXT lib)
else()
set(PACKAGE_EXT a)
endif()

foreach(ITEM ${PACKAGE_ITEMS})
	message(STATUS "adding item ${ITEM}")

	add_library(${CMAKE_FIND_PACKAGE_NAME}::${ITEM} STATIC IMPORTED)

if(PACKAGE_MULTI_INC)
	set_target_properties(${CMAKE_FIND_PACKAGE_NAME}::${ITEM} PROPERTIES 
							INTERFACE_INCLUDE_DIRECTORIES "${PACKAGE_DIR}/$(HOST)/$(PLATFORM)/include/")
else()
	set_target_properties(${CMAKE_FIND_PACKAGE_NAME}::${ITEM} PROPERTIES 
							INTERFACE_INCLUDE_DIRECTORIES "${PACKAGE_DIR}/include/")
endif()
	
	set_property(TARGET ${CMAKE_FIND_PACKAGE_NAME}::${ITEM} APPEND 
							PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
	set_property(TARGET ${CMAKE_FIND_PACKAGE_NAME}::${ITEM} APPEND 
							PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)

	set_target_properties(${CMAKE_FIND_PACKAGE_NAME}::${ITEM} PROPERTIES
							IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
							IMPORTED_LOCATION_RELEASE "${PACKAGE_DIR}/${HOST}/${PLATFORM}/lib${ITEM}.${PACKAGE_EXT}")
	set_target_properties(${CMAKE_FIND_PACKAGE_NAME}::${ITEM} PROPERTIES
							IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
							IMPORTED_LOCATION_NOCONFIG "${PACKAGE_DIR}/${HOST}/${PLATFORM}/lib${ITEM}.${PACKAGE_EXT}")
endforeach()

# Commands beyond this point should not need to know about these
unset(PACKAGE_DIR)
unset(PACKAGE_ITEMS)
unset(PACKAGE_EXT)
unset(PACKAGE_MULTI_INC)
